import { Artist, CountryInfo } from './types';

// Country list with flags for popular radio countries
export const COUNTRIES: CountryInfo[] = [
  { name: 'México', code: 'MX', stationCount: 0, flag: '🇲🇽' },
  { name: 'Estados Unidos', code: 'US', stationCount: 0, flag: '🇺🇸' },
  { name: 'España', code: 'ES', stationCount: 0, flag: '🇪🇸' },
  { name: 'Argentina', code: 'AR', stationCount: 0, flag: '🇦🇷' },
  { name: 'Colombia', code: 'CO', stationCount: 0, flag: '🇨🇴' },
  { name: 'Perú', code: 'PE', stationCount: 0, flag: '🇵🇪' },
  { name: 'Chile', code: 'CL', stationCount: 0, flag: '🇨🇱' },
  { name: 'Venezuela', code: 'VE', stationCount: 0, flag: '🇻🇪' },
  { name: 'Ecuador', code: 'EC', stationCount: 0, flag: '🇪🇨' },
  { name: 'Guatemala', code: 'GT', stationCount: 0, flag: '🇬🇹' },
  { name: 'Cuba', code: 'CU', stationCount: 0, flag: '🇨🇺' },
  { name: 'Bolivia', code: 'BO', stationCount: 0, flag: '🇧🇴' },
  { name: 'Rep. Dominicana', code: 'DO', stationCount: 0, flag: '🇩🇴' },
  { name: 'Honduras', code: 'HN', stationCount: 0, flag: '🇭🇳' },
  { name: 'Paraguay', code: 'PY', stationCount: 0, flag: '🇵🇾' },
  { name: 'Uruguay', code: 'UY', stationCount: 0, flag: '🇺🇾' },
  { name: 'El Salvador', code: 'SV', stationCount: 0, flag: '🇸🇻' },
  { name: 'Nicaragua', code: 'NI', stationCount: 0, flag: '🇳🇮' },
  { name: 'Costa Rica', code: 'CR', stationCount: 0, flag: '🇨🇷' },
  { name: 'Panamá', code: 'PA', stationCount: 0, flag: '🇵🇦' },
  { name: 'Brasil', code: 'BR', stationCount: 0, flag: '🇧🇷' },
  { name: 'Reino Unido', code: 'GB', stationCount: 0, flag: '🇬🇧' },
  { name: 'Alemania', code: 'DE', stationCount: 0, flag: '🇩🇪' },
  { name: 'Francia', code: 'FR', stationCount: 0, flag: '🇫🇷' },
  { name: 'Italia', code: 'IT', stationCount: 0, flag: '🇮🇹' },
  { name: 'Japón', code: 'JP', stationCount: 0, flag: '🇯🇵' },
];

// Popular genres/tags for radio
export const GENRES = [
  'Pop',
  'Rock',
  '80s',
  '90s',
  'Latin',
  'Regional Mexicano',
  'Reggaeton',
  'Electronic',
  'Dance',
  'Hip Hop',
  'Jazz',
  'Classical',
  'Country',
  'R&B',
  'Soul',
  'Folk',
  'Blues',
  'Metal',
  'Punk',
  'Alternative',
  'Indie',
  'News',
  'Talk',
  'Sports',
  'Oldies',
  'Hits',
  'Top 40',
  'Christian',
  'Gospel',
];

// Sample Artists Data (Mock data for MVP)
export const SAMPLE_ARTISTS: Artist[] = [
  {
    id: 'duran-duran',
    name: 'Duran Duran',
    genre: 'Pop Rock, New Wave, Synth-pop',
    origin: 'Birmingham, Reino Unido',
    yearsActive: '1978 - presente',
    bio: 'Duran Duran es una banda británica de new wave y synth-pop formada en Birmingham en 1978. Fueron uno de los grupos más exitosos de los años 80 y pioneros del video musical en MTV. La banda está compuesta por Simon Le Bon (voz), Nick Rhodes (teclados), John Taylor (bajo) y Roger Taylor (batería). Con más de 100 millones de discos vendidos mundialmente, son conocidos por éxitos como "Hungry Like the Wolf", "Rio", "Save A Prayer" y "Ordinary World". Su estilo visual innovador y sus producciones cinematográficas los convirtieron en íconos de la era MTV.',
    image: '',
    topSongs: [
      { id: 'dd1', title: 'Hungry Like the Wolf', artist: 'Duran Duran', duration: '3:41' },
      { id: 'dd2', title: 'Rio', artist: 'Duran Duran', duration: '5:14' },
      { id: 'dd3', title: 'Save A Prayer', artist: 'Duran Duran', duration: '5:29' },
      { id: 'dd4', title: 'Girls on Film', artist: 'Duran Duran', duration: '3:30' },
      { id: 'dd5', title: 'Ordinary World', artist: 'Duran Duran', duration: '5:02' },
      { id: 'dd6', title: 'Come Undone', artist: 'Duran Duran', duration: '4:15' },
      { id: 'dd7', title: 'Wild Boys', artist: 'Duran Duran', duration: '4:03' },
      { id: 'dd8', title: 'Notorious', artist: 'Duran Duran', duration: '4:18' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/2M2RhTsA0tBcsGfoXPbWJw',
      youtube: 'https://www.youtube.com/results?search_query=Duran+Duran',
      wikipedia: 'https://en.wikipedia.org/wiki/Duran_Duran',
    }
  },
  {
    id: 'stereo-rey',
    name: 'Stereo Rey',
    genre: 'Regional Mexicano, Grupero',
    origin: 'Monterrey / Aguascalientes / México',
    yearsActive: '1980 - presente',
    bio: 'Stereo Rey es una emblemática cadena de estaciones de radio mexicana que transmite música regional mexicana, grupero y latinos. Con presencia en múltiples ciudades de México incluyendo Monterrey, Aguascalientes y otras importantes plazas, Stereo Rey se ha convertido en sinónimo de música para el pueblo mexicano. Su programación incluye éxitos de artistas como Los Tigres del Norte, Banda MS, Julión Álvarez y muchos más. Es favorita entre los amantes de la música tradicional mexicana contemporánea.',
    image: '',
    topSongs: [
      { id: 'sr1', title: 'La Mejor de Todas - Banda MS', artist: 'Stereo Rey', duration: '3:45' },
      { id: 'sr2', title: 'El Taxista - Julión Álvarez', artist: 'Stereo Rey', duration: '3:22' },
      { id: 'sr3', title: 'Yo También - Román Urrego', artist: 'Stereo Rey', duration: '3:18' },
      { id: 'sr4', title: 'Las Que Se Ponen Bien Perla - Banda MS', artist: 'Stereo Rey', duration: '2:58' },
      { id: 'sr5', title: 'Para Exaltarte - El Fantasma', artist: 'Stereo Rey', duration: '3:05' },
      { id: 'sr6', title: 'Juro Que Te Amo - Los Temerarios', artist: 'Stereo Rey', duration: '3:42' },
      { id: 'sr7', title: 'Mi Vicio - Grupo Firme', artist: 'Stereo Rey', duration: '2:55' },
      { id: 'sr8', title: 'El Amor No Fue Para Mí - Christian Nodal', artist: 'Stereo Rey', duration: '3:28' },
    ],
    links: {
      youtube: 'https://www.youtube.com/results?search_query=Stereo+Rey+Radio',
    }
  },
  {
    id: 'los-bukis',
    name: 'Los Bukis',
    genre: 'Grupero, Balada, Ranchera',
    origin: 'Ario de Rosales, Michoacán, México',
    yearsActive: '1975 - 1996 / Reunión 2021',
    bio: 'Los Bukis fue una legendaria banda mexicana de música grupero fundada por Marco Antonio Solís ("El Buki Mayor"). Considerados como los reyes del género grupero, la banda revolucionó la música latina con baladas románticas que conquistaron toda Latinoamérica. Éxitos como "A Donde Vas", "Tu Cárcel", "Como Fui a Enamorarme de Ti" y "Y Ahora Te Vas" son himnos inolvidables. Tras su separación en 1996, Marco Antonio Solís continuó con exitosa carrera como solista, y en 2021 la banda se reunió para una histórica gira mundial.',
    image: '',
    topSongs: [
      { id: 'lb1', title: 'A Donde Vas', artist: 'Los Bukis', duration: '4:12' },
      { id: 'lb2', title: 'Tu Cárcel', artist: 'Los Bukis', duration: '4:35' },
      { id: 'lb3', title: 'Como Fui a Enamorarme de Ti', artist: 'Los Bukis', duration: '4:48' },
      { id: 'lb4', title: 'Y Ahora Te Vas', artist: 'Los Bukis', duration: '3:55' },
      { id: 'lb5', title: 'Acepte Mi Error', artist: 'Los Bukis', duration: '4:22' },
      { id: 'lb6', title: 'Me Di Cuenta', artist: 'Los Bukis', duration: '3:38' },
      { id: 'lb7', title: 'Falso Amor', artist: 'Los Bukis', duration: '4:15' },
      { id: 'lb8', title: 'Como Quisiera Decirte', artist: 'Los Bukis', duration: '4:02' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/2pcE5L0NywRwtPaiMZcAy9',
      youtube: 'https://www.youtube.com/results?search_query=Los+Bukis',
      wikipedia: 'https://es.wikipedia.org/wiki/Los_Bukis',
    }
  },
  {
    id: 'mana',
    name: 'Maná',
    genre: 'Rock Pop, Rock Latino, Alternativo',
    origin: 'Guadalajara, Jalisco, México',
    yearsActive: '1986 - presente',
    bio: 'Maná es una banda mexicana de rock formada en Guadalajara en 1986. Considerada como la banda de rock en español más exitosa de la historia, han vendido más de 40 millones de discos worldwide. La formación actual incluye Fher Olvera (voz), Alex González (batería), Sergio Vallín (guitarra) y Juan Calleros (bajo). Con numerosos Grammy Latinos y Grammy americanos, sus conciertos masivos llenan estadios en todo el mundo. Sus letras abordan temas desde el amor hasta la ecología.',
    image: '',
    topSongs: [
      { id: 'm1', title: 'Oye Mi Amor', artist: 'Maná', duration: '4:16' },
      { id: 'm2', title: 'Vivir Sin Aire', artist: 'Maná', duration: '4:55' },
      { id: 'm3', title: 'Rayando el Sol', artist: 'Maná', duration: '5:04' },
      { id: 'm4', title: 'Labios Compartidos', artist: 'Maná', duration: '4:28' },
      { id: 'm5', title: 'Mariposa Traicionera', artist: 'Maná', duration: '4:52' },
      { id: 'm6', title: 'Clavado en un Bar', artist: 'Maná', duration: '5:08' },
      { id: 'm7', title: 'El Rey Tiburón', artist: 'Maná', duration: '4:35' },
      { id: 'm8', title: 'Hechicera', artist: 'Maná', duration: '4:42' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/3YQKlSSj56fP1GvhxT0ZSv',
      youtube: 'https://www.youtube.com/results?search_query=Mana+Oficial',
      wikipedia: 'https://es.wikipedia.org/wiki/Man%C3%A1_(banda)',
    }
  },
  {
    id: 'cafe-tacvba',
    name: 'Café Tacvba',
    genre: 'Rock Alternativo, Indie, Folklorico',
    origin: 'Ciudad de México, México',
    yearsActive: '1989 - presente',
    bio: 'Café Tacvba (estilizado como Café Tacvba) es una banda mexicana de rock alternativo formada en 1989 en Ciudad de México. Conocidos por su versatilidad musical que fusiona rock, folklor mexicano, punk, electronic y más, son considerados pioneros del rock latino alternativo. La banda está formada por Rubén Albarrán (voz), Emmanuel del Real (teclados, guitarra), Joselo Rangel (guitarra) y Quique Rangel (bajo). Su album "Re" es considerado uno de los mejores discos de rock en español de todos los tiempos.',
    image: '',
    topSongs: [
      { id: 'ct1', title: 'La Ingrata', artist: 'Café Tacvba', duration: '2:35' },
      { id: 'ct2', title: 'Eres', artist: 'Café Tacvba', duration: '4:52' },
      { id: 'ct3', title: 'Las Flores', artist: 'Café Tacvba', duration: '4:08' },
      { id: 'ct4', title: 'María', artist: 'Café Tacvba', duration: '4:42' },
      { id: 'ct5', title: 'El Baile y el Salón', artist: 'Café Tacvba', duration: '3:55' },
      { id: 'ct6', title: 'El París, no es México', artist: 'Café Tacvba', duration: '4:28' },
      { id: 'ct7', title: 'Olita de Altamar', artist: 'Café Tacvba', duration: '3:32' },
      { id: 'ct8', title: 'Ingrata', artist: 'Café Tacvba', duration: '2:38' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/4saFhdqIJUWWDTU8XU0Z3p',
      youtube: 'https://www.youtube.com/results?search_query=Cafe+Tacvba',
      wikipedia: 'https://es.wikipedia.org/wiki/Caf%C3%A9_Tacvba',
    }
  },
  {
    id: 'bad-bunny',
    name: 'Bad Bunny',
    genre: 'Reggaeton, Latin Trap, Hip Hop',
    origin: 'Almirante Sur, Vega Baja, Puerto Rico',
    yearsActive: '2016 - presente',
    bio: 'Benito Antonio Martínez Ocasio, conocido profesionalmente como Bad Bunny, es un cantante y rapero puertorriqueño. Conocido como el artista principal del movimiento de reggaeton moderno, ha roto récords de streaming y se ha convertido en un fenómeno global. Sus canciones abordan temas sociales, emocionales y de celebración. Con álbumes como "X100PRE", "YHLQMDLG" y "Un Verano Sin Ti", Bad Bunny ha llevado la música latina a nuevos horizontes, colaborando con artistas de todos los géneros.',
    image: '',
    topSongs: [
      { id: 'bb1', title: 'Tití Me Preguntó', artist: 'Bad Bunny', duration: '4:03' },
      { id: 'bb2', title: 'Me Porto Bonito', artist: 'Bad Bunny', duration: '4:25' },
      { id: 'bb3', title: 'Dakiti', artist: 'Bad Bunny feat. Jhay Cortez', duration: '3:20' },
      { id: 'bb4', title: 'I Like It', artist: 'Cardi B, Bad Bunny & J Balvin', duration: '4:13' },
      { id: 'bb5', title: 'Mia', artist: 'Bad Bunny feat. Drake', duration: '4:50' },
      { id: 'bb6', title: 'Callaita', artist: 'Bad Bunny feat. Tainy', duration: '4:18' },
      { id: 'bb7', title: 'Amorfoda', artist: 'Bad Bunny', duration: '3:55' },
      { id: 'bb8', title: 'Vete', artist: 'Bad Bunny', duration: '3:28' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
      youtube: 'https://www.youtube.com/results?search_query=Bad+Bunny+Oficial',
      wikipedia: 'https://en.wikipedia.org/wiki/Bad_Bunny',
    }
  },
  {
    id: 'shakira',
    name: 'Shakira',
    genre: 'Pop, Latin Pop, Reggaeton',
    origin: 'Barranquilla, Colombia',
    yearsActive: '1990 - presente',
    bio: 'Shakira Isabel Mebarak Ripoll, conocida simplemente como Shakira, es una cantautora colombiana. Debutó a principios de los 90 y se consolidó como una de las artistas latinas más importantes del mundo. Con más de 80 millones de discos vendidos, es conocida por su voz única, sus coreografías y su versatilidad musical. Álbumes como "Pies Descalzos", "Dónde Están los Ladrones?", "Laundry Service" y "El Dorado" contienen éxitos globales. Ha ganado múltiples Grammy, Grammy Latinos y es embajadora de UNICEF.',
    image: '',
    topSongs: [
      { id: 'sk1', title: 'Hips Don\'t Lie', artist: 'Shakira feat. Wyclef Jean', duration: '3:38' },
      { id: 'sk2', title: 'Waka Waka', artist: 'Shakira', duration: '3:22' },
      { id: 'sk3', title: 'Chantaje', artist: 'Shakira feat. Maluma', duration: '3:30' },
      { id: 'sk4', title: 'La Bicicleta', artist: 'Shakira feat. Carlos Vives', duration: '3:47' },
      { id: 'sk5', title: 'Ojos Así', artist: 'Shakira', duration: '3:51' },
      { id: 'sk6', title: 'Suerte', artist: 'Shakira', duration: '3:42' },
      { id: 'sk7', title: 'Ciega, Sordomuda', artist: 'Shakira', duration: '4:28' },
      { id: 'sk8', title: 'Te Felicito', artist: 'Shakira feat. Rauw Alejandro', duration: '3:45' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/0DwK3oYQSOf4XN68U70fsB',
      youtube: 'https://www.youtube.com/results?search_query=Shakira+Oficial',
      wikipedia: 'https://en.wikipedia.org/wiki/Shakira',
    }
  },
  {
    id: 'rosalia',
    name: 'Rosalía',
    genre: 'Pop, Flamenco, Reggaeton Urbano',
    origin: 'San Cugat del Vallés, Barcelona, España',
    yearsActive: '2013 - presente',
    bio: 'Rosalia Vila Tobella, conocida artísticamente como Rosalía, es una cantautora española originaria de Barcelona. Ha revolucionado la música fusionando flamenco tradicional con pop urbano, reggaeton y música experimental. Tras estudiar flamenco académico, irrumpió con "Los Ángeles" (2017) y consagró con "El Mal Querer" (2018), álbum que le valió un Grammy Latino y reconocimiento global. Colaboraciones con J Balvin, Bad Bunny y Travis Scott la han posicionado como artista de vanguardia internacional.',
    image: '',
    topSongs: [
      { id: 'rs1', title: 'Despechá', artist: 'Rosalía', duration: '2:39' },
      { id: 'rs2', title: 'Saoko', artist: 'Rosalía', duration: '2:52' },
      { id: 'rs3', title: 'Malamente', artist: 'Rosalía', duration: '2:49' },
      { id: 'rs4', title: 'Di Mi Nombre', artist: 'Rosalía', duration: '3:12' },
      { id: 'rs5', title: 'Pienso en tu Mirá', artist: 'Rosalía', duration: '2:38' },
      { id: 'rs6', title: 'Juro Que Me Voy', artist: 'Rosalía & Raül Refree', duration: '3:28' },
      { id: 'rs7', title: 'TKN', artist: 'Rosalía feat. Travis Scott', duration: '2:53' },
      { id: 'rs8', title: 'La Fama', artist: 'Rosalía feat. The Weeknd', duration: '3:11' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/0COkNCfJ0YJMz5tEqsXwrm',
      youtube: 'https://www.youtube.com/results?search_query=Rosalia+Oficial',
      wikipedia: 'https://en.wikipedia.org/wiki/Rosal%C3%ADa_(singer)',
    }
  },
  {
    id: 'juan-gabriel',
    name: 'Juan Gabriel',
    genre: 'Ranchera, Mariachi, Pop Latino',
    origin: 'Parácuaro, Michoacán, México',
    yearsActive: '1971 - 2016',
    bio: 'Alberto Aguilera Valadez, conocido mundialmente como Juan Gabriel, fue un cantautor, productor e intérprete mexicano. Conocido como "Divo de Juárez" o "El Divo de América", fue uno de los artistas más prolíficos e influyentes de la música latina. Escribió aproximadamente 1800 canciones, muchas de ellas convertidas en clásicos. Con una carrera de más de 45 años, sus emotivas rancheras y baladas como "Se Me Olvidó Otra Vez", "Abrázame Muy Fuerte" y "Amor Eterno" son himnos de la cultura hispana.',
    image: '',
    topSongs: [
      { id: 'jg1', title: 'Amor Eterno', artist: 'Juan Gabriel', duration: '5:02' },
      { id: 'jg2', title: 'Se Me Olvidó Otra Vez', artist: 'Juan Gabriel', duration: '3:28' },
      { id: 'jg3', title: 'Abrázame Muy Fuerte', artist: 'Juan Gabriel', duration: '3:45' },
      { id: 'jg4', title: 'Asi Fue', artist: 'Juan Gabriel', duration: '4:12' },
      { id: 'jg5', title: 'Hasta Que Te Conoci', artist: 'Juan Gabriel', duration: '3:58' },
      { id: 'jg6', title: 'La Diferencia', artist: 'Juan Gabriel', duration: '3:35' },
      { id: 'jg7', title: 'Pero Que Necesidad', artist: 'Juan Gabriel', duration: '3:22' },
      { id: 'jg8', title: 'No Tengo Dinero', artist: 'Juan Gabriel', duration: '2:58' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/6VEJzuuWyLYtKvu78aG7sJ',
      youtube: 'https://www.youtube.com/results?search_query=Juan+Gabriel',
      wikipedia: 'https://es.wikipedia.org/wiki/Juan_Gabriel',
    }
  },
  {
    id: 'the-weeknd',
    name: 'The Weeknd',
    genre: 'R&B, Pop, Synth-pop',
    origin: 'Toronto, Ontario, Canadá',
    yearsActive: '2010 - presente',
    bio: 'Abel Makkonen Tesfaye, conocido profesionalmente como The Weeknd, es un cantautor canadiense. Conocido por su característico falsete y su producción sónica innovadora, ha emergido como uno de los artistas más exitosos de la década reciente. Sus mixtapes iniciales ("House of Balloons", "Thursday", "Echoes of Silence") establecieron su sonido oscuro y atmosférico. Álbumes como "Beauty Behind the Madness", "Starboy" y "After Hours" han generado múltiples número uno mundialmente.',
    image: '',
    topSongs: [
      { id: 'tw1', title: 'Blinding Lights', artist: 'The Weeknd', duration: '3:20' },
      { id: 'tw2', title: 'Save Your Tears', artist: 'The Weeknd', duration: '3:35' },
      { id: 'tw3', title: 'Starboy', artist: 'The Weeknd feat. Daft Punk', duration: '3:50' },
      { id: 'tw4', title: 'Die For You', artist: 'The Weeknd', duration: '4:20' },
      { id: 'tw5', title: 'Can\'t Feel My Face', artist: 'The Weeknd', duration: '3:35' },
      { id: 'tw6', title: 'The Hills', artist: 'The Weeknd', duration: '4:02' },
      { id: 'tw7', title: 'Earned It', artist: 'The Weeknd', duration: '4:30' },
      { id: 'tw8', title: 'Take My Breath', artist: 'The Weeknd', duration: '4:10' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/1Xyo4u8VXCBlZaen7QEDFU',
      youtube: 'https://www.youtube.com/results?search_query=The+Weeknd+Official',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Weeknd',
    }
  },
  {
    id: 'grupo-firme',
    name: 'Grupo Firme',
    genre: 'Regional Mexicano, Banda, Norteño',
    origin: 'Tijuana, Baja California, México',
    yearsActive: '2014 - presente',
    bio: 'Grupo Firme es una banda mexicana de regional mexicano formada en Tijuana en 2014. Liderada por Eduardo "Pano" (voz), la banda ha revolucionado el género con su energía única y conexión con las nuevas generaciones. Con múltiples premios包括 Grammy Latinos y Billboard Latin Music Awards, se han convertido en una de las bandas más populares del momento. Sus conciertos agotan estadios en todo el continente americano y sus videos tienen millones de reproducciones.',
    image: '',
    topSongs: [
      { id: 'gf1', title: 'Pedida', artist: 'Grupo Firme', duration: '2:55' },
      { id: 'gf2', title: 'El Toxico', artist: 'Grupo Firme', duration: '3:12' },
      { id: 'gf3', title: 'Ya Superame', artist: 'Grupo Firme', duration: '2:48' },
      { id: 'gf4', title: 'Cada Vez', artist: 'Grupo Firme feat. Maluma', duration: '3:22' },
      { id: 'gf5', title: 'Mi Vicio', artist: 'Grupo Firme', duration: '2:55' },
      { id: 'gf6', title: 'Enseñame a Olvidar', artist: 'Grupo Firme', duration: '3:05' },
      { id: 'gf7', title: 'Supongo', artist: 'Grupo Firme', duration: '2:42' },
      { id: 'gf8', title: 'Las Que Se Ponen Bien Perla', artist: 'Grupo Firme', duration: '2:58' },
    ],
    links: {
      spotify: 'https://open.spotify.com/artist/4SQDhShKvXMYxeO4lpXJAq',
      youtube: 'https://www.youtube.com/results?search_query=Grupo+Firme+Oficial',
      wikipedia: 'https://es.wikipedia.org/wiki/Grupo_Firme',
    }
  },
];

// RadioBrowser API Base URL
export const RADIO_BROWSER_API = 'https://de1.api.radio-browser.info';
